name: deployment exercise 1
on: push
jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: getCode
          uses: actions/checkout@3
        - name: Install Dependencies
          run: npm ci
        - name: lint
          run: npm run lint
    test:
      runs-on: ubuntu-latest
      steps:
        - name: getCode
          uses: actions/checkout@3
        - name: Install Dependencies
          run: npm ci
        - name: Test
          run: npm run test
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: getCode
              uses: actions/checkout@3
            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: deploy
              run: echo "deploying"